### ISSUE TITLE
Single trial approach modelling scripts

### ISSUE THREAD

**Issue by elsie-h** [opensafely/covid-vaccine-effectiveness-sequential-vs-single#1]
@wjchulme please review the following:

I've made some changes to the modelling scripts to avoid hitting memory limits, please review all modelling scripts [in this folder](https://github.com/opensafely/covid-vaccine-effectiveness-sequential-vs-single/tree/main/analysis/single/model), see the [project.yaml](https://github.com/opensafely/covid-vaccine-effectiveness-sequential-vs-single/blob/3df382b1aca1edada1df4ba13191433923bc5dc1/project.yaml#L978) for the run order.

I've removed `vax1_date + maxfup` from the `lastfup_date` definition, as it meant that we couldn't plot brand12counts properly, [here's the commit](https://github.com/opensafely/covid-vaccine-effectiveness-sequential-vs-single/commit/00e79d16eecf3f76410a4768ecb76b8052808986).

**Comment by wjchulme** [comment]
Happy with this. Hopefully it won't cause any more memory issues. There's some additional refactoring we could do to simplify for new readers (eg where is `tidy_plr` and what does it do? -- we could just pull all that into the main msm script). But I think this should come later.
